#include <bits/stdc++.h>
using namespace std;

void solve(std::string b)
{
    if (b == "A")
        puts("T");
    else if (b == "T")
        puts("A");
    else if (b == "G")
        puts("C");
    else
        puts("G");
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string b;
    std::cin >> b;
    solve(b);
    return 0;
}
