/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;


class ADoubleHelix {
public:
    void solve(std::istream &in, std::ostream &out) {
      char b;
      in >> b;
      switch (b) {
        case 'A':
          out << 'T' << endl;
          break;
        case 'C':
          out << 'G' << endl;
          break;
        case 'G':
          out << 'C' << endl;
          break;
        case 'T':
          out << 'A' << endl;
          break;
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  ADoubleHelix solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
