/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long


class AChristmasEveEveEve {
public:
    void solve(std::istream &in, std::ostream &out) {
      int d;
      in >> d;
      switch (d) {
        case 25:
          out << "Christmas" << endl;
          break;
        case 24:
          out << "Christmas Eve" << endl;
          break;
        case 23:
          out << "Christmas Eve Eve" << endl;
          break;
        case 22:
          out << "Christmas Eve Eve Eve" << endl;
          break;
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  AChristmasEveEveEve solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
