#include <bits/stdc++.h>
using namespace std;


void solve(long long a, long long b, long long x){
  double depth = (double)(x)/a/a;
  double ad = a;
  double bd = b;
  double L, theta;
  if(depth>bd/2){
    L = sqrt(ad*ad + 4*(bd-depth)*(bd-depth));
    theta = acos(a/L)/2.0/3.1415926589*360;
  } else {
    double y = 2.0*x/ad/bd;
    L = sqrt(bd*bd+y*y);
    theta = acos(y/L)/2.0/3.1415926589*360;
  }
  cout << setprecision(12) << theta << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long a;
    scanf("%lld",&a);
    long long b;
    scanf("%lld",&b);
    long long x;
    scanf("%lld",&x);
    solve(a, b, x);
    return 0;
}
