#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";


// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    vector<string> inp(2);
    for(long long i = 0; i < 2; i++){
      cin >> inp[i];
    }

    for(long long i = 0; i < 2; i++) {
      for(long long j = 0; j < 3; j++) {
        if(inp[i][j] != inp[1-i][2-j]) goto err;
      }
    }

    cout << YES << endl;
    return 0;
    err:

    cout << NO << endl;
    return 0;
}
