#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<long long> a) {
  int ans = 0;
  for(int i = 0 ; i < N ; ){
    int j = i;
    while( j < N && a[j] == a[i] ) j++;
  	ans += (j - i) / 2;
    i = j;
  }
  cout << ans << endl;  
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  long long N;
  scanf("%lld", &N);
  std::vector<long long> a(N);
  for (int i = 0; i < N; i++) {
    scanf("%lld", &a[i]);
  }
  solve(N, std::move(a));
  return 0;
}
