#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> a){
  bool nextjump = false;
  long long count = 0;
  for(long long i = 1; i < N; i++) {
    if(nextjump){
      nextjump = false;
      continue;
    }

    if(a[i-1] == a[i]) {
      count++;
      nextjump = true;
    }
  }

  cout << count << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> a(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&a[i]);
  }
    solve(N, std::move(a));
    return 0;
}
