/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long


class AStillTBD {
public:
    void solve(std::istream &in, std::ostream &out) {
      string s;
      in >> s;
      int y = stoll(s.substr(0, 4));
      int m = stoll(s.substr(5, 2));
      int d = stoll(s.substr(8, 2));
      if (y < 2019) {
        out << "Heisei" << endl;
      } else if (y == 2019) {
        if (m <= 4) {
          out << "Heisei" << endl;
        } else {
          out << "TBD" << endl;
        }
      } else {
        out << "TBD" << endl;
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  AStillTBD solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
