/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define D double
#define int long long
#define outdicimal out << fixed << setprecision(10)//TODO 小数点以下の桁数の変更


class AEntranceExamination {
public:
    void solve(std::istream &in, std::ostream &out) {
      int t, x;
      in >> t >> x;
      outdicimal << (D) t / x << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  AEntranceExamination solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
