#include <bits/stdc++.h>
#define REP(i, n) for (int i=0;i<(n);i++)
#define ALL(v) v.begin(), v.end()
#define INF 1e9
#define ll long long
#define P pair<ll, ll>

using namespace std;


void solve(std::string S){
    ll cnt0 = 0;
    ll cnt1 = 0;
    REP(i, S.length()){
        if (S[i] == '0') cnt0++;
        else cnt1++;
    }
    ll ans = 2*min(cnt0, cnt1);
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
