#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, long long M)
{
    for (ll i = M; i >= 1; i--) {
        if ((M % 2 == 1 && i % 2 == 1) || (M % 2 == 0 && i % 2 == 0)) {
            cout << 1 + ((M - i + 1) / 2) << " " << M + 1 - ((M - i + 1) / 2) << endl;
        } else {
            cout << 1 + ((M - i + 1) / 2) + M << " " << M + 1 - ((M - i + 1) / 2) + M + 1 << endl;
        }
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    solve(N, M);
    return 0;
}
