#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long M){
    int count = 1;
    if (N % 2 == 1) {
        for (int i = 2; i <= (N+1)/2; i++) {
            cout << i << " " << (N - i + 2) << endl;
            if (count >= M) return;
            count++;
        }
    } else {
        for (int i = 2; i <= (N+1)/2; i++) {
            if (i <= (N/2+1)/2) {
                cout << i << " " << (N - i + 2) << endl;
            } else {
                cout << i << " " << (N - i + 1) << endl;
            }
            if (count >= M) return;
            count++;
        }
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    solve(N, M);
    return 0;
}
