#include <bits/stdc++.h>
using namespace std;


void solve(long long a, long long b) {

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main() {
    long long aa, bb;
    cin >> aa >> bb;
    string a_tan, b_tan, a, b;
    a_tan = to_string(aa);
    b_tan = to_string(bb);
    for (int i=0;i<bb;i++)
        a += a_tan;

    for (int i=0;i<aa;i++)
        b += b_tan;

    if (a<b)
        cout << a << endl;
    else
        cout << b << endl;

}
