/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)


class CColoringColorfully {
public:
    void solve(std::istream &in, std::ostream &out) {
      string s;
      in >> s;
      int ans = 0;
      char search = s[0];
      FOR(i, 1, s.length()) {
        if (search == s[i]) {
          ans++;
          search = s[i] == '0' ? '1' : '0';
        } else {
          search = s[i];
        }
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  CColoringColorfully solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
