/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class CColoringColorfully {
public:
    void solve(istream& cin, ostream& cout) {
        string s;
        cin >> s;
        int o0 = 0, o1 = 0, e0 = 0, e1 = 0;
        int n = s.length();
        int o = n/2, e = n/2;
        if(n % 2 == 1) o++;
        for(int i=0; i<n; i++) {
            if(i%2)
                (s[i] == '0') ? o0++ : o1++;
            else
                (s[i] == '0') ? e0++ : e1++;
        }
        cout << min(o1+e0, o0+e1) << '\n';
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    CColoringColorfully solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
