/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class CColoringColorfully {
public:
    void solve(std::istream &in, std::ostream &out) {
      string s;
      in >> s;
      vector<string> ss(2, "");
      REP(i, s.length()) {
        ss[i % 2] += "0";
        ss[(i + 1) % 2] += "1";
      }
      int t0 = 0, t1 = 0;
      REP(i, s.length()) {
        if (s[i] != ss[0][i]) {
          t0++;
        } else if (s[i] != ss[1][i]) {
          t1++;
        }
      }
      out << min(t0, t1) << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  CColoringColorfully solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
