/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long


class ARatedForMe {
public:
    void solve(std::istream &in, std::ostream &out) {
      int r;
      in >> r;
      if (r < 1200) {
        out << "ABC" << endl;
      } else if (r < 2800) {
        out << "ARC" << endl;
      } else {
        out << "AGC" << endl;
      }
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  ARatedForMe solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
