/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author tommy6073
 */

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

class ARatedForMe {
public:
    void solve(std::istream& in, std::ostream& out) {
        int R;
        in >> R;

        string result;
        if (R < 1200) {
            result = "ABC";
        } else if (R < 2800) {
            result = "ARC";
        } else {
            result = "AGC";
        }

        out << result;
    }
};


int main() {
	ARatedForMe solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
