#include <bits/stdc++.h>
using namespace std;


void solve(long long H, long long W, long long A, long long B){
    for (int i=0;i<H;i++){
        for (int j=0;j<W;j++){
            int ret = 0;
            if (i<B && j <A) ret = 1;
            if (i>=B && j>=A) ret=1;
            printf("%d",ret);
        }
        printf("\n");
    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    scanf("%lld",&H);
    long long W;
    scanf("%lld",&W);
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    solve(H, W, A, B);
    return 0;
}
