#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

void solve(long long N, std::vector<long long> A, std::vector<long long> B){
    vector<ll> AB(N,0);
    for (int i=0;i<N;i++){
        AB[i]  = A[i] + B[i];
    }
    sort(AB.begin(),AB.end());
    ll res = 0;
    for (int i=0;i<N;i++){
        res -= B[i];
    }
    for (int i=N-1;i>=0;i-=2){
        res += AB[i];
    }

    printf("%lld\n",res);

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    std::vector<long long> B(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
        scanf("%lld",&B[i]);
    }
    solve(N, std::move(A), std::move(B));
    return 0;
}
