/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))
typedef vector<int> vec;


class CSpecialTrains {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n;
    in >> n;
    vec c(n - 1), s(n - 1), f(n - 1);
    REP(i, n-1) in >> c[i] >> s[i] >> f[i];
    REP(i, n ) {
      int t = 0;
      FOR(j,i,n - 1){
        if(t < s[j]) t = s[j];
        else if(t % f[j] == 0) t += 0;
        else t = t + f[j] - (t % f[j]);
        t += c[j];
      }
      out << t << endl;
    }
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	CSpecialTrains solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
