/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
typedef vector<int> vec;


class ATaskSchedulingProblem {
public:
    void solve(std::istream &in, std::ostream &out) {
      vector<int> a(3);
      REP(i, 3) in >> a[i];

      vec b;
      REP(i, 2) FOR(j, i + 1, 3) {
          b.push_back(abs(a[i] - a[j]));
        }
      sort(b.begin(), b.end());
      out << b[0] + b[1] << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  ATaskSchedulingProblem solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
