#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

const string YES = "Yes";
const string NO = "No";

void solve(vector<vector<long long>> A, long long N, vector<long long> b) {
    string ans = NO;
    bool card[3][3] = {false};

    for (int i = 0; i < N; i++) {
        for (int ai = 0; ai < 3; ai++) {
            for (int aj = 0; aj < 3; aj++) {
                if (A[ai][aj] == b[i]) {
                    card[ai][aj] = true;
                }
            }
        }
    }

    // bingo check, row
    for (int i = 0; i < 3; i++) {
        bool is_bingo = card[i][0] && card[i][1] && card[i][2];
        if (is_bingo) ans = YES;
    }

    // bingo check, column
    for (int i = 0; i < 3; i++) {
        bool is_bingo = card[0][i] && card[1][i] && card[2][i];
        if (is_bingo) ans = YES;
    }

    // bingo check, left cross
    if (card[0][0] && card[1][1] && card[2][2]) ans = YES;

    // bingo check, right cross
    if (card[0][2] && card[1][1] && card[2][0]) ans = YES;

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  vector<vector<long long>> A(3, vector<long long>(3));
  for (int i = 0; i < 3; i++) {
    for (int j = 0; j < 3; j++) {
      cin >> A[i][j];
    }
  }
  long long N;
  cin >> N;
  vector<long long> b(N);
  for (int i = 0; i < N; i++) {
    cin >> b[i];
  }
  solve(move(A), N, move(b));
  return 0;
}
