#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;

void solve(std::string S, long long K){
    ll N = S.size();
    vector<ll> vec;
    for(int i=0;i<N;i++){
        ll num =1;
        while(i+1<N && S[i] == S[i+1]){
            num++;
            i++;
        }
        vec.push_back(num);
    }
    if(vec.size()==1){
        cout << (K*N)/2 << endl;
        return;
    }

    ll midsize =0;
    for(int i=1;i<vec.size()-1;i++){
        midsize += vec[i]/2;
    }

    if(S[0] == S[N-1]){
         cout << (vec.front()/2) + midsize*K + (vec.back()/2) +((vec.front() + vec.back())/2)*(K-1) << endl;
    }else{
        cout << (vec.front()/2 + midsize + vec.back()/2)*K << endl;
    }


}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    long long K;
    scanf("%lld",&K);
    solve(S, K);
    return 0;
}
