#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> s){
    std::sort(s.begin(), s.end());
    int sum = 0;
    for ( auto it = s.begin(); it != s.end();  ) {
       auto f = *it;
       it++;
       auto s =  *it;
       it++;
       sum += std::min(f, s);
    }
    std::cout << sum << std::endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> L(2*N);
    for(int i = 0 ; i < 2*N ; i++){
        scanf("%lld",&L[i]);
    }
    solve(N, std::move(L));
    return 0;
}
