/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class BShiritori {
public:
    void solve(istream& cin, ostream& cout) {
        int n;
        cin >> n;
        vector<string> s;
        for(int i=0; i<n; i++) {
            string tp; cin >> tp;
            s.push_back(tp);
        }
        bool flag = true;
        for(int i=1; i<n; i++) {
            if(s[i][0] != s[i-1][s[i-1].length()-1]) flag = false;
            for(int j=i-1; j>=0; j--) {
                if(s[j].compare(s[i]) == 0) flag = false;
            }
        }
        cout << ((flag) ? "Yes" : "No") << '\n';
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    BShiritori solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
