#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long C){
  //どこかが1つ足りない
  //2箇所1足りない
  long long current;
  long long tarinai;
  if(A >= B && A >= C) {
    current = ((A-B)/2)+((A-C)/2);
    tarinai = ((A-B)%2)+((A-C)%2);
  }
  else if(B >= A && B >= C) {
    current = ((B-A)/2)+((B-C)/2);
    tarinai = ((B-A)%2)+((B-C)%2);
  }
  else if(C >= B && C >= A) {
    current = ((C-B)/2)+((C-A)/2);
    tarinai = ((C-B)%2)+((C-A)%2);
  }

  if(tarinai == 1){
    cout << current+2 << endl;
  }
  else if(tarinai == 2){
    cout << current+1 << endl;
  }
  else{
    cout << current << endl;
  }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long C;
  scanf("%lld",&C);
    solve(A, B, C);
    return 0;
}
