#include <bits/stdc++.h>
using namespace std;


void solve(long long X, long long Y){
  if(X % Y == 0) {
    cout << -1 << endl;
    return;
  }

  for(long long i = 2; i < LLONG_MAX; i++){
    if((X*i)%Y != 0) {
      cout << (X*i) << endl;
      break;
    }
  }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long X;
  scanf("%lld",&X);
  long long Y;
  scanf("%lld",&Y);
    solve(X, Y);
    return 0;
}
