#include <bits/stdc++.h>
using namespace std;


void solve(long long X, long long A, long long B){
  if((A-B) >= 0) {
    cout << "delicious" << endl;
  }
  else {
    cout << (((A-B) + X >= 0) ? "safe" : "dangerous") << endl;
  }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long X;
  scanf("%lld",&X);
  long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
    solve(X, A, B);
    return 0;
}
