/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author tommy6073
 */

#include <iostream>
#include <string>

using namespace std;

class AGarden {
public:
    void solve(std::istream& in, std::ostream& out) {
        int A, B;
        in >> A >> B;

        out << (A - 1) * (B - 1) << endl;
    }
};


int main() {
	AGarden solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
