/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long


class BCollatzProblem {
public:
    void solve(std::istream &in, std::ostream &out) {
      vector<bool> a(1e6 + 1, false);
      int s;
      in >> s;
      a[s] = true;
      int now = s;
      int i = 1;
      while (true) {
        i++;
        if (now % 2 == 0) {
          if (a[now / 2]) break;
          else {
            a[now / 2] = true;
            now = now / 2;
          }
        } else {
          if (a[3 * now + 1]) break;
          else {
            a[3 * now + 1] = true;
            now = 3 * now + 1;
          }
        }
      }
      out << i << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BCollatzProblem solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
