/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <cstdio>
#include <cstring>
#include <cmath>
#include <utility>
#include <iostream>
#include <functional>
#include <bitset>
#include <algorithm>
#include <vector>
#include <forward_list>
#include <set>
#include <map>
#include <queue>
#include <deque>
#include <stack>
#include <numeric>
#include <iomanip>
#define ll long long int
#define rep(i,n) for(int i=0;i<(n);i++)
#define pb push_back
using namespace std;
int mx4[] = {0,1,0,-1};
int my4[] = {1,0,-1,0};
int mx2[] = {1,0};
int my2[] = {0,1};

int main(){
        int s; cin >> s;
        vector<int> a(1000001);
        if(s == 1) {
          cout << 4 << endl;
          return 0;
        }if(s == 2) {
          cout << 4 << endl;
          return 0;
        }else{
            a[0] = s;
            for (int i = 0; i < 1000001; i++) {
                if (a[i] % 2 == 0) a[i + 1] = a[i] / 2;
                else a[i + 1] = 3 * a[i] + 1;
            }
            for (int i = 0; i < 1000000; i++) {
                if (a[i] == 4) {
                    cout << i + 4 << endl;
                    break;
                }
            }
        }
	}
