/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class BChocolate {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n,d,x;
    in >> n >> d >> x;
    vector<int> a(n);
    REP(i,n) in >> a[i];
    int cnt = 0;
    REP(i, n){
      cnt += (d - 1) / a[i] + 1;
    }
    out << cnt + x << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BChocolate solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
