#include <bits/stdc++.h>
using namespace std;

int mygcd(int m, int n) {
  if(n==0) {
    return m;
  }
  else {
    return mygcd(n, m % n);
  }
}

long long mylcm(long long a, long long b) {
    return a * b / mygcd(a, b);
}

void solve(long long A, long long B, long long C, long long D){
  long long a = (A-1)/C;
  a += (A-1)/D;

  long long b = B/C;
  b += B/D;

  long long l = mylcm(C,D);


  cout << (((B-b)+(B/l)) - (((A-1)-a)+((A-1)/l)))<< endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long C;
  scanf("%lld",&C);
  long long D;
  scanf("%lld",&D);
    solve(A, B, C, D);
    return 0;
}
