#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) { if (a > b) { a = b; return 1; } return 0; }
template <class T> inline bool dpmax(T &a, T b) { if (a < b) { a = b; return 1; } return 0; }

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main()
{
    long long N;
    cin >> N;

    ll ans = 0;
    for (int i = 1; i <= N; i+=2) {
        int n_div = 0;
        for (int j = 1; j <= i; j+=2) {
            if (i%j == 0) { n_div++; }
        }

        if (n_div == 8) { ans++; }
    }

    cout << ans << endl;

    return 0;
}
