/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long


class CMultipleGift {
public:
    void solve(std::istream &in, std::ostream &out) {
      int x, y;
      in >> x >> y;
      int t = x;
      int ans = 0;
      while (t <= y) {
        ans++;
        t *= 2;
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  CMultipleGift solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
