#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(std::vector<long long> a, std::vector<long long> b){
  map<long long, long long> tab;

  for(long long i = 0; i < 3; i++){
    tab[a[i]]++;
    tab[b[i]]++;
  }

  long long one_edge = 0;
  long long two_edge = 0;

  for(long long i = 1; i <= 4; i++){
    if(tab[i] == 1) one_edge++;
    if(tab[i] == 2) two_edge++;
  }

  cout << ((one_edge == 2 && two_edge == 2) ? YES : NO) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::vector<long long> a(3);
  std::vector<long long> b(3);
  for(int i = 0 ; i < 3 ; i++){
    scanf("%lld",&a[i]);
    scanf("%lld",&b[i]);
  }
    solve(std::move(a), std::move(b));
    return 0;
}
