/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class BAcCepted {
public:
    void solve(istream& cin, ostream& cout) {
        string s; cin >> s;
        bool flag = true;
        if(s[0] != 'A') flag = false;
        int n = s.length(); int cnt = 0;
        for(int i=2; i<n-1; i++) {
            if(s[i] == 'C') cnt++;
        }
        if(cnt != 1) flag = false;
        for(auto k: s) {
            if(k != 'A' && k != 'C') {
                if(k > 'z' || k  < 'a') flag = false;
            }
        }
        cout << ((flag) ? "AC\n": "WA\n");
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    BAcCepted solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
