//クドイやり方しか見つけられず
#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S){
    sort(S.begin(),S.end());
    puts((S[0] == S[1] && S[1] != S[2]&&S[2] ==S[3]) ? "Yes" : "No");
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
