#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long M, long long K)
{
    ll a_max = (ll)pow(2, M) - 1;

    if (K > a_max) {
        cout << -1 << endl;
        return;
    }
    if (M == 0) {
        cout << "0 0" << endl;
        return;
    }
    if (M == 1) {
        if (K == 0) {
            cout << "0 0 1 1" << endl;
            return;
        } else {
            cout << -1 << endl;
            return;
        }
    }
    if (M >= 2) {
        for (int i = 0; i <= a_max; i++ ) {
            if (i == K) {
                continue;
            }
            cout << i << " ";
        }
        cout << K << " ";
        for (int i = a_max; i >= 0; i--) {
            if (i == K) {
                continue;
            }
            cout << i << " ";
        }
        cout << K << endl;
    }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
// clang-format off
int main(){
    long long M;
    scanf("%lld",&M);
    long long K;
    scanf("%lld",&K);
    solve(M, K);
    return 0;
}
