#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(long long N, vector<long long> v) {
    sort(v.begin(), v.end());
    vector<double> x(N);
    rep(i, N) {
        x[i] = double(v[i]);
    }

    double tmp_val;
    while (x.size() > 1) {
        tmp_val = x[0] + x[1];
        tmp_val /= 2;
        x.erase(x.begin());
        x.erase(x.begin());
        x.push_back(tmp_val);
        sort(x.begin(), x.end());
    }
    cout << x[0] << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  cin >> N;
  vector<long long> v(N);
  for (int i = 0; i < N; i++) {
    cin >> v[i];
  }
  solve(N, move(v));
  return 0;
}
