/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long

class BAtCoderBeginnerContest111 {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n;
      in >> n;
      int t = 111;
      int i = 1;
      while (n > t) {
        i++;
        t = 111 * i;
      }
      out << 111 * i << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BAtCoderBeginnerContest111 solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
