/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author tommy6073
 */

#include <iostream>
#include <string>

using namespace std;

class AGrouping2 {
public:
    void solve(std::istream& in, std::ostream& out) {
        int N;
        in >> N;

        out << N / 3;
    }
};


int main() {
	AGrouping2 solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
