#include <bits/stdc++.h>
using namespace std;

void solve(std::string s) {
string rick;
  for(int i = 1;i<=s.size();i++){
    if(i%2)rick+=s[i-1];
  }
  cout<<rick;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  std::string s;
  std::cin >> s;
  solve(s);
  return 0;
}
