#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)

ll sub(ll A, ll B){
    if(A == 0 || B == 0){
        return 0;
    }
    if(A > B){
        return sub(B, A);
    }

    if(B % A == 0){
        return (B / A) * 2 * A - A;
    }else{
        return (B / A) * 2 * A + sub(A, B % A);
    }
}

void solve(long long N, long long X){
    cout << N + sub(X, N - X) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long N;
    scanf("%lld",&N);
    long long X;
    scanf("%lld",&X);
    solve(N, X);
    return 0;
}
