#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

void solve(long long N, long long X){
    ll ret = N;
    ll a = max(N-X,X);
    ll b = min(N-X,X);
    while(1){
        ll q = a/b;
        ll r = a%b;
        ret += 2 * (a/b ) * b;
        if (r==0){
            ret -= b;
            break;
        }
        a = b;
        b = r;
    }
    printf("%lld\n",ret);
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long X;
    scanf("%lld",&X);
    solve(N, X);
    return 0;
}
