#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> a){
  multimap<long long, long long> tab;

  for(long long i = 1; i <= N; i++) {
    tab.emplace(a[i], i);
  }

  long long count = 0;
  for(long long i = 1; i <= N; i++) {
    auto it = tab.equal_range(i);
    for(auto j = it.first; j != it.second; j++) {
      if(j->second == a[i]) count++;
    }
  }

  cout << count/2 << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> a(N+1);
  for(int i = 1 ; i <= N ; i++){
    scanf("%lld",&a[i]);
  }
    solve(N, std::move(a));
    return 0;
}
