/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(int i = 0; i < (int)(n); i++)
#define all(v) v.begin(), v.end()

class AABProblem {
public:
	void solve(std::istream& in, std::ostream& out) {
	    ll n,a,b;
	    in>>n>>a>>b;
	    if(a>b){
	        out<<0<<endl;
            return;
	    } else if(n==1 && a!=b){
	        out<<0<<endl;
            return;
	    } else if(n==1){
	        out<<1<<endl;
            return;
	    }

	    out<<(b-a)*(n-2)+1<<endl;




	}
};


int main() {
	AABProblem solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
