#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> H){
  long long mymax = H[0];
  long long count = 1;
  for(long long i = 1; i < N; i++){
    if(mymax <= H[i]) {
      mymax = H[i];
      count++;
    }
  }

  cout << count << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> H(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&H[i]);
  }
    solve(N, std::move(H));
    return 0;
}
