#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(long long N, vector<long long> X) {
    ll min_hp = 1e8;

    for (int i = 1; i <= 100; i++) {
        ll hp = 0;
        for (int j=0; j < N; j++) {
            hp += (X[j] - i) * (X[j] - i);
        }
        if (hp <= min_hp) min_hp = hp;
    }

    cout << min_hp << endl;

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  cin >> N;
  vector<long long> X(N);
  for (int i = 0; i < N; i++) {
    cin >> X[i];
  }
  solve(N, move(X));
  return 0;
}
