#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

int solve(long long N, std::vector<long long> t, std::vector<long long> x, std::vector<long long> y)
{
    for (int i = 1; i <= N; i++)
    {
        long long dt = t[i] - t[i - 1];
        long long dx_dy = abs(x[i] - x[i - 1]) + abs(y[i] - y[i - 1]);
        if (dt < dx_dy || dt % 2 != dx_dy % 2)
        {
            cout << "No" << endl;
            return 0;
        }
    }

    cout << "Yes" << endl;
    return 0;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<long long> t(N + 1, 0);
    std::vector<long long> x(N + 1, 0);
    std::vector<long long> y(N + 1, 0);
    for (int i = 1; i <= N; i++)
    {
        scanf("%lld", &t[i]);
        scanf("%lld", &x[i]);
        scanf("%lld", &y[i]);
    }
    solve(N, std::move(t), std::move(x), std::move(y));
    return 0;
}
