/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))
typedef vector<int> vec;


class CTraveling {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n;
    in >> n;
    vector<int> t(n);
    vec x(n), y(n);
    REP(i,n) {
      in >> t[i] >> x[i] >> y[i];
    }
    int oldt = 0,oldx = 0, oldy = 0;
    REP(i, n){
      int t1 = t[i] - oldt;
      int t2 = abs(x[i] - oldx + y[i] - oldy);
      if(t1 % 2 != t2 % 2 || t1 < t2){
        out << "No" << endl;
        return;
      }
      oldt = t[i]; oldx = x[i]; oldy = y[i];
    }
    out << "Yes" << endl;

	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	CTraveling solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
