#include <bits/stdc++.h>
using namespace std;

const long long MOD = 2;

void solve(long long N, long long P, std::vector<long long> A) {
	int one  = 0;
  long long tmp = 0;
  for(int i  =0 ;i<N;i++)if(A[i]%2)one = 1;
     if(one == 0){
		if(P == 1)tmp = 0;
       else tmp = 1ll<<N;
     }
      else tmp = 1ll<<N-1;
  cout<<tmp<<'\n';
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You
// use the default template now. You can remove this line by using your custom
// template)
int main() {
  long long N;
  scanf("%lld", &N);
  long long P;
  scanf("%lld", &P);
  std::vector<long long> A(N);
  for (int i = 0; i < N; i++) {
    scanf("%lld", &A[i]);
  }
  solve(N, P, std::move(A));
  return 0;
}
