#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using P = pair<ll,ll>;
const string YES = "Yes";
const string NO = "No";

void solve(std::string S, std::string T){
    vector<vector<int>> sAlpha(26),tAlpha(26);
    for(int i=0;i<S.size();i++){
        int s = S[i] -'a';
        sAlpha[s].push_back(i);
    }
    set<char> alreadyChecked;
    for(int i=0;i<26;i++){
        if(sAlpha[i].size()==0){
            continue;
        }
        // cerr <<"i="<< i<<endl;
        char t = T[sAlpha[i][0]];
        if(alreadyChecked.find(t) != alreadyChecked.end()){
            cout << NO << endl;
            return;
        }
        // cerr <<"t=" << t << endl;
        for(int j=0;j<sAlpha[i].size();j++){
            // cerr <<"j=" << j << endl;
            if(T[sAlpha[i][j]]  != t){
                cout << NO <<endl;
                return;
            }
        }
        alreadyChecked.insert(t);
    }
    cout <<YES << endl;


}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    solve(S, T);
    return 0;
}
