/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long


class AProduct {
public:
	void solve(std::istream& in, std::ostream& out) {
    int a,b;
    in >> a >> b;
    int t = a * b;
    if(t % 2 == 0){
      out << "Even" << endl;
    }
    else{
      out << "Odd" << endl;
    }
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	AProduct solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
