/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;


class AAbcOfABC {
public:
	void solve(std::istream& in, std::ostream& out) {
    string s;
    in >> s;
    sort(s.begin(),s.end());
    if(s == "abc"){
      out << "Yes" << endl;
    }
    else{
      out << "No" << endl;
    }
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	AAbcOfABC solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
