#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)

const string YES = "YES";
const string NO = "NO";

void solve(std::vector<long long> N){
    sort(N.begin(), N.end());
    if(N[0] == 1 && N[1] == 4 && N[2] == 7 && N[3] == 9){
        cout << YES << endl;
    }else{
        cout << NO << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    std::vector<long long> N(4);
    for(int i = 0 ; i < 4 ; i++){
        scanf("%lld",&N[i]);
    }
    solve(std::move(N));
    return 0;
}
