#include <bits/stdc++.h>
using namespace std;

long long gcd(long long a, long long b) {
    if (a < b) {
        a ^= b;
        b ^= a;
        a ^= b;
    }

    return b ? gcd(b, a % b) : a;
}

void solve(long long N, long long X, std::vector<long long> x){
  sort(x.begin(), x.end(), [&](auto a, auto b){ return abs(X - a) < abs(X - b); });

  long long acc = abs(X - x[0]);

  for(long long i = 1; i < N; i++){
    acc = gcd(acc, abs(X - x[i]));
  }

  cout << acc << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  long long X;
  scanf("%lld",&X);
  std::vector<long long> x(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&x[i]);
  }
    solve(N, X, std::move(x));
    return 0;
}
