#include <bits/stdc++.h>
using namespace std;

void solve(std::string S){
  long long N = S.size()+1;
  vector<long long> tab(N);

  for(long long i = 0; i < (N-1); i++) {
    if(S[i] == '<') tab[i+1] = max(tab[i+1], tab[i] + 1);
  }

  for(long long i = (N-2); i >= 0; i--) {
    if(S[i] == '>') tab[i] = max(tab[i], tab[i+1] + 1);
  }

  cout << accumulate(tab.begin(), tab.end(), 0ll) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
  std::cin >> S;
    solve(S);
    return 0;
}
