#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

//  < > > <
// 0 2 1 0 1
void solve(string S) {
    ll n = S.size(), ans = 0;
    vector<ll> a(n+1, 0);

    for (int i = 0; i <= n - 1; i++) {
        if (S[i] == '<') {
            dpmax(a[i+1], a[i]+1);
        }
    }

    for (int i = n - 1; i >= 0; i--) {
        if (S[i] == '>') {
            dpmax(a[i], a[i+1]+1);
        }
    }

    for (int i = 0; i <= n; i++) {
        ans += a[i];
    }
    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  string S;
  cin >> S;
  solve(S);
  return 0;
}
