#include <bits/stdc++.h>
using namespace std;

const string YES = "Possible";
const string NO = "Impossible";

void solve(long long A, long long B){
  if(A%3==0||B%3==0||(A+B)%3==0) cout<<YES<<endl;
  else cout<<NO<<endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    solve(A, B);
    return 0;
}
