/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class BCakesAndDonuts {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n;
      in >> n;
      REP(i, 30) REP(j, 20) {
          if (n == 4 * i + 7 * j) {
            out << "Yes" << endl;
            return;
          }
        }
      out << "No" << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BCakesAndDonuts solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
