#include <bits/stdc++.h>
#define REP(i, n) for (int i=0;i<(n);i++)
#define ALL(v) v.begin(), v.end()
#define INF 1e9
#define ll long long
#define P pair<ll, ll>

using namespace std;


void solve(long long N, std::vector<long long> h){
    vector<ll> vec(N);
    vec[0] = h[0];
    ll cnt = 0;
    REP(i,N-1) vec[i+1] = h[i+1]-h[i];
    REP(i,N) if (vec[i] > 0) cnt += vec[i];
    cout << cnt << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> h(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&h[i]);
    }
    solve(N, std::move(h));
    return 0;
}
