#include <bits/stdc++.h>
#include <atcoder/dsu>
using namespace std;
using namespace atcoder;
typedef long long ll;
const ll INF = 1e18;
const ll MOD = 1e9+7;
#define REP(i,j,n) for(int i=j;i<n;i++)
#define rep(i,n) REP(i,0,n)

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    cin.tie(0);
    ios::sync_with_stdio(false);

    int n,q;
    cin >> n >> q;

    dsu d(n);
    rep(i,q)
    {
        int t,u,v;
        cin >> t >> u >> v;
        if (t==0)
        {
           d.merge(u, v);
        }
        else
        {
            cout << d.same(u, v) << endl;
        }
    }
    return 0;
}
