#include <bits/stdc++.h>
#define REP(i, n) for (int i=0;i<(n);i++)
#define ALL(v) v.begin(), v.end()
#define INF 1e9

typedef long long ll;

using namespace std;


void solve(long long N, long long M, std::vector<long long> A, std::vector<long long> B){
    vector<pair<ll,ll>> vec(N);
    REP(i,N) vec[i] = pair<ll,ll>(A[i],B[i]);

    ll rest = M;
    ll cost = 0;

    sort(ALL(vec));

    for (int i=0;rest>0;i++){
        cost += vec[i].first * min(vec[i].second, rest);
        rest -= min(vec[i].second, rest);
    }
    cout << cost << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> A(N);
    std::vector<long long> B(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
        scanf("%lld",&B[i]);
    }
    solve(N, M, std::move(A), std::move(B));
    return 0;
}
