#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::string s, std::string t){
  for(long long i = 0; i < N; i++) {
    if(equal(s.begin()+i, s.end(), t.begin())) {
      cout << N+i << endl;
      return;
    }
  }

  cout << (N*2) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::string s;
  std::cin >> s;
  std::string t;
  std::cin >> t;
    solve(N, s, t);
    return 0;
}
