#include <iostream>
#include <string>
#include <cstdio>
#include <vector>
#include <stdio.h>
#include <algorithm>
#include <functional>
#include <queue>
#include <math.h>
#include <cmath>
#include <unordered_map>

#define rep(i,n) for (int i = 0; i < (n); ++i)
using namespace std;



void solve(std::string S, std::string T){
    int ans=T.length();
    rep(i, S.length()-T.length()+1){
        //cout<<S[i]<<endl;
        int cnt=0;
        rep(j,T.length()){
            if(S[i+j]!=T[j])cnt++;
        }
        ans=min(cnt,ans);
    }
    cout<<ans<<endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    solve(S, T);
    return 0;
}
