#include <bits/stdc++.h>
using namespace std;

#define rep(i, N) for (long long i = 0; i < N; i++)
using ll = long long;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S) {
    string revS = S;
    reverse(revS.begin(), revS.end());
    if (S == revS) {
        string S2 = "";
        for (ll i = 0; i < (S.length() - 1) / 2; i++) {
            S2.push_back(S[i]);
        }
        string S3 = "";
        for (ll i = (S.length() + 3) / 2 - 1; i < S.length(); i++) {
            S3.push_back(S[i]);
        }
        string revS2 = S2;
        string revS3 = S3;
        reverse(revS2.begin(), revS2.end());
        reverse(revS3.begin(), revS3.end());
        if (S2 == revS2 && S3 == revS3) {
            cout << YES << endl;
            return;
        }
    }
    cout << NO << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
