#include <bits/stdc++.h>
using namespace std;


void solve(std::string S, long long w){
  for(long long i = 0; i < S.size(); i++){
    if(i%w == 0) cout << S[i];
  }

  cout << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
  std::cin >> S;
  long long w;
  scanf("%lld",&w);
    solve(S, w);
    return 0;
}
