#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define REP(i,n) for (ll i = 0; i < (n); ++i)


void solve(long long A, long long B, long long K){
    REP(i, K){
        if(i % 2 == 0){
            A -= A % 2;
            B += A / 2;
            A /= 2;
        }else{
            B -= B % 2;
            A += B / 2;
            B /= 2;
        }
    }
    cout << A << ' ' << B << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long K;
    scanf("%lld",&K);
    solve(A, B, K);
    return 0;
}
