/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class BTwoColorsCardGame {
public:
	void solve(std::istream& in, std::ostream& out) {
    int n;
    in >> n;
    vector<string> s(n);
    REP(i,n) in >> s[i];

    int m;
    in >> m;
    vector<string> t(m);
    REP(i,m) in >> t[i];

    map<string, int> a;
    REP(i,n){
      a[s[i]]++;
    }
    REP(i,m){
      a[t[i]]--;
    }
    out << max(0ll, max_element(a.begin(),a.end(),[](pair<string, int> b, pair<string, int> c){return b.second < c.second;})->second) << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BTwoColorsCardGame solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
