#include <bits/stdc++.h>
using namespace std;

void solve(long long P, long long Q, long long R)
{
    vector<long long> A = {P, Q, R};
    long long M = P + Q + R;

    M = min(M, A[0] + A[1]);
    M = min(M, A[0] + A[2]);
    M = min(M, A[1] + A[2]);

    cout << M << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long P;
    scanf("%lld", &P);
    long long Q;
    scanf("%lld", &Q);
    long long R;
    scanf("%lld", &R);
    solve(P, Q, R);
    return 0;
}
