/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class CDubiousDocument2 {
public:
    void solve(std::istream &in, std::ostream &out) {
      string s, t;
      in >> s >> t;
      vector<string> ss;
      REP(i, s.length() - t.length() + 1) {
        string u = s.substr(i, t.length());
        bool f = true;
        REP(j, u.length()) {
          f &= (u[j] == t[j] || u[j] == '?');
        }
        if (f) {
          string v = s.substr(0, i) + t + s.substr(i + t.length(), s.length() - t.length() - i);
          REP(j, v.length()) {
            if (v[j] == '?') v[j] = 'a';
          }
          ss.push_back(v);
        }
      }
      if (!ss.empty()) {
        sort(ss.begin(), ss.end());
        out << ss[0] << endl;
      } else {
        out << "UNRESTORABLE" << endl;
      }

    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  CDubiousDocument2 solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
