/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include <iostream>
#include <fstream>

#include "bits/stdc++.h"

using namespace std;
#define int long long


class AApplePie {
public:
    void solve(std::istream &in, std::ostream &out) {
      int a, p;
      in >> a >> p;
      p += a * 3;
      int ans = 0;
      while (p >= 2) {
        ans++;
        p -= 2;
        p = max(0ll, p);
      }
      out << ans << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  AApplePie solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
