#include <bits/stdc++.h>
using namespace std;

void solve(long long A, long long P)
{
    P += A * 3;
    long long Pi = floor(P / 2);
    cout << Pi << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long P;
    scanf("%lld", &P);
    solve(A, P);
    return 0;
}
