#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long C, long long K){
  cout << (((K%2) == 0) ? (A - B) : ((B+C) - (A+C))) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long C;
  scanf("%lld",&C);
  long long K;
  scanf("%lld",&K);
    solve(A, B, C, K);
    return 0;
}
