/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))
#define SP << " " <<


class BRuinedSquare {
public:
    void solve(std::istream &in, std::ostream &out) {
      int x1, y1, x2, y2;
      in >> x1 >> y1 >> x2 >> y2;
      int a = x2 - x1;
      int b = y2 - y1;
      int tx = x2;
      int ty = y2;
      REP(i, 2) {
        swap(a, b);
        a *= -1;
        tx += a;
        ty += b;
        out << tx SP ty << " ";
      }
      out << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  BRuinedSquare solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
