#include <vector>
#include <string>
#include <map>
#include <algorithm>
#include <queue>
#include <iostream>
#include <cmath>

#define REP(i,n) for(ll i=0;i<(ll)(n);i++)
#define REPD(i,n) for(ll i=n-1;i>=0;i--)
#define FOR(i,a,b) for(ll i=a;i<=(ll)(b);i++)
#define FORD(i,a,b) for(ll i=a;i>=(ll)(b);i--)
typedef long long ll;
using namespace std;


void solve(int N, std::vector<long double> A) {
    long double res = 1;
    REP(i, N) { 
        if (A[i] == 0) { 
            cout << 0 << endl;
            return;
        }
    }

    REP(i, N) { 
        res *= A[i];
        // cout << res << endl;
        if (res > (long double)1e18) { 
            cout << -1 << endl;
            return ;
        }
    }
    cout << (long long)res << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    int N;
    scanf("%d",&N);
    std::vector<long double> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%Lf",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
