#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

ll n,p[100005],ind1,ind2,ind3,ind4;
string s;


int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(0); cout.tie(0);

    cin>>n>>s;
    /////////////////////////////////////////
    p[0]=1; p[1]=-1;
    for(ll i=2;i<=n-1;i++)
    {
        if(i==n-1)
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
            if(s[i]=='o')
            {
                if(p[i]==1)
                {
                    if(p[i-1]!=p[0])
                        ind1=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind1=1;
                }
            }
            else
            {
                if(p[i]==-1)
                {
                    if(p[i-1]!=p[0])
                        ind1=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind1=1;
                }
            }
            if(s[0]=='o')
            {
                if(p[0]==1)
                {
                    if(p[n-1]!=p[1])
                        ind1=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind1=1;
                }
            }
            else
            {
                if(p[0]==-1)
                {
                    if(p[n-1]!=p[1])
                        ind1=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind1=1;
                }
            }
        }
        else
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
        }
    }
    if(ind1==0)
    {
        for(ll i=0;i<n;i++)
            if(p[i]==1)
                cout<<'S';
            else
                cout<<'W';
        cout<<endl;
        return 0;
    }
    memset(p,0,100005);
    /////////////////////////////////////////
    p[0]=1; p[1]=1;
    for(ll i=2;i<=n-1;i++)
    {
        if(i==n-1)
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
            if(s[i]=='o')
            {
                if(p[i]==1)
                {
                    if(p[i-1]!=p[0])
                        ind2=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind2=1;
                }
            }
            else
            {
                if(p[i]==-1)
                {
                    if(p[i-1]!=p[0])
                        ind2=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind2=1;
                }
            }
            if(s[0]=='o')
            {
                if(p[0]==1)
                {
                    if(p[n-1]!=p[1])
                        ind2=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind2=1;
                }
            }
            else
            {
                if(p[0]==-1)
                {
                    if(p[n-1]!=p[1])
                        ind2=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind2=1;
                }
            }
        }
        else
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
        }
    }
    if(ind2==0)
    {
        for(ll i=0;i<n;i++)
            if(p[i]==1)
                cout<<'S';
            else
                cout<<'W';
        cout<<endl;
        return 0;
    }
    memset(p,0,100005);
    /////////////////////////////////////////
    p[0]=-1; p[1]=-1;
    for(ll i=2;i<=n-1;i++)
    {
        if(i==n-1)
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
            if(s[i]=='o')
            {
                if(p[i]==1)
                {
                    if(p[i-1]!=p[0])
                        ind3=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind3=1;
                }
            }
            else
            {
                if(p[i]==-1)
                {
                    if(p[i-1]!=p[0])
                        ind3=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind3=1;
                }
            }
            if(s[0]=='o')
            {
                if(p[0]==1)
                {
                    if(p[n-1]!=p[1])
                        ind3=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind3=1;
                }
            }
            else
            {
                if(p[0]==-1)
                {
                    if(p[n-1]!=p[1])
                        ind3=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind3=1;
                }
            }
        }
        else
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
        }
    }
    if(ind3==0)
    {
        for(ll i=0;i<n;i++)
            if(p[i]==1)
                cout<<'S';
            else
                cout<<'W';
        cout<<endl;
        return 0;
    }
    memset(p,0,100005);
    /////////////////////////////////////////
    p[0]=-1; p[1]=1;
    for(ll i=2;i<=n-1;i++)
    {
        if(i==n-1)
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
            if(s[i]=='o')
            {
                if(p[i]==1)
                {
                    if(p[i-1]!=p[0])
                        ind4=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind4=1;
                }
            }
            else
            {
                if(p[i]==-1)
                {
                    if(p[i-1]!=p[0])
                        ind4=1;
                }
                else
                {
                    if(p[i-1]==p[0])
                        ind4=1;
                }
            }
            if(s[0]=='o')
            {
                if(p[0]==1)
                {
                    if(p[n-1]!=p[1])
                        ind4=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind4=1;
                }
            }
            else
            {
                if(p[0]==-1)
                {
                    if(p[n-1]!=p[1])
                        ind4=1;
                }
                else
                {
                    if(p[n-1]==p[1])
                        ind4=1;
                }
            }
        }
        else
        {
            if(s[i-1]=='o')
            {
                if(p[i-1]==1)
                    p[i]=p[i-2];
                else
                    p[i]=-p[i-2];
            }
            else
            {
                if(p[i-1]==1)
                    p[i]=-p[i-2];
                else
                    p[i]=p[i-2];
            }
        }
    }
    if(ind4==0)
    {
        for(ll i=0;i<n;i++)
            if(p[i]==1)
                cout<<'S';
            else
                cout<<'W';
        cout<<endl;
        return 0;
    }

    cout<<-1<<endl;

    return 0;
}
