#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long double> x, std::vector<std::string> u){
  long double acc = 0;
  for(long long i = 0; i < N; i++){
    if(u[i] == "BTC"){
      acc += (x[i] * 380000.0);
    }
    else{
      acc += x[i];
    }
  }

  cout << std::fixed << std::setprecision(20) << acc << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long double> x(N);
  std::vector<std::string> u(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%Lf",&x[i]);
    std::cin >> u[i];
  }
    solve(N, std::move(x), std::move(u));
    return 0;
}
