/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class B1DimensionalWorldsTale {
public:
    void solve(std::istream &in, std::ostream &out) {
      int n, m, x, y;
      in >> n >> m >> x >> y;
      vector<int> vx(n);
      REP(i, n) in >> vx[i];
      vector<int> vy(m);
      REP(i, m) in >> vy[i];
      sort(vx.begin(), vx.end(), greater<int>());
      sort(vy.begin(), vy.end(), less<int>());
      FOR(i, x + 1, y + 1) {
        if (vx[0] < i && vy[0] >= i) {
          out << "No War" << endl;
          return;
        }
      }
      out << "War" << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  B1DimensionalWorldsTale solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
