#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

int solve(long long N, long long A)
{

    for (int i = 0; i <= A; i++)
    {
        long long coin = 0;
        while (true)
        {

            if (1 * i + 500 * coin == N)
            {
                cout << "Yes" << endl;
                return 0;
            }
            else if (500 * coin > N)
            {
                break;
            }
            coin++;
        }
    }

    cout << "No" << endl;
    return 0;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    long long A;
    scanf("%lld", &A);
    solve(N, A);
    return 0;
}
