#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(long long K) {
    ll x, n_lun = 0;
    queue<ll> q;

    for (ll i = 1; i <= 9; i++) {
        q.push(i);
    }

    while (n_lun < K) {
        n_lun++;
        x = q.front();
        q.pop();

        if (x%10 != 0) {
            q.push(x*10 + (x%10) - 1);
        }
        q.push(x*10 + (x%10));
        if (x%10 != 9) {
            q.push(x*10 + (x%10) + 1);
        }
    }

    cout << x << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long K;
  cin >> K;
  solve(K);
  return 0;
}
