#include <bits/stdc++.h>
using namespace std;
#define rep(i, N) for (long long i = 0; i < N; i++)
using ll = long long;

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
    ll N, K;
    cin >> N >> K;
    vector<ll> sunuke(N + 1);
    rep(i, K) {
        ll d;
        cin >> d;
        vector<ll> A(d);
        rep(j, d) {
            ll a;
            cin >> a;
            sunuke[a]++;
        }
    }
    ll ans = 0;
    for (ll i = 1; i <= N; i++) {
        if (sunuke[i] == 0) {
            ans++;
        }
    }
    cout << ans << endl;
    return 0;
}
