#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

// 3 3 4 2 4
// 1 0 0 0 0
// 0 0 1 0 0
// 0 0 1 0 0
void solve(long long N, vector<long long> a) {
    ll ans = 0, current = 0;
    while (1) {
        if (current == 1) {
            break;
        }
        if (ans >= N) {
            ans = -1;
            break;
        }
        ans++;
        current = a[current] - 1;
    }

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  long long N;
  cin >> N;
  vector<long long> a(N);
  for (int i = 0; i < N; i++) {
    cin >> a[i];
  }
  solve(N, move(a));
  return 0;
}
