#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A){
  long double acc = 0;
  for(long long i = 0; i < N; i++){
    acc += (1.0l/A[i]);
  }

  cout << (1.0/acc) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  std::vector<long long> A(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&A[i]);
  }
    solve(N, std::move(A));
    return 0;
}
