#include <bits/stdc++.h>
using namespace std;


void solve(long long K, long long A, long long B){
  if((A+1) < B && K >= A) {
    cout << (A + (((((K+1)-A)/2) * (B - A)) + (((K+1)-A)%2))) << endl;
  }
  else {
    cout << (K + 1) << endl;
  }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long K;
  scanf("%lld",&K);
  long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
    solve(K, A, B);
    return 0;
}
