#include <bits/stdc++.h>
using namespace std;


void solve(long long N){
  map<long long, long long> counts;
  long long count = 0;
  for(long long i = 1; i <= N; i++){
    counts[floor((long double)log10(i))+1]++;
    if((long long)(floor((long double)log10(i))+1) % 2 == 1) count++;
  }

  cout << count << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
    solve(N);
    return 0;
}
