/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <string>
#include <vector>
#include <math.h>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <bitset>
using namespace std;
using ll = long long;
constexpr ll INF = 1010000000000000017LL;
#define rep(i, n) for(ll i = 0; i < (ll)(n); i++)
#define all(v) v.begin(), v.end()

ll GCD(ll a, ll b) { if(b==0) return a; else return GCD(b, a%b); }
ll LCM(ll a, ll b) { return a/GCD(a,b)*b; }

class C {
public:
	void solve(std::istream& in, std::ostream& out) {
        ll n;in>>n;
        vector<vector<ll>> vv(n,vector<ll> (26,0));

        rep(i,n){
            string s;in>>s;
            rep(j,s.size()){
                vv.at(i).at(s.at(j)-'a')++;
            }
        }

        string res;
        rep(j,26){
            ll cnt=51;
            rep(i,n){
                cnt=min(cnt,vv.at(i).at(j));
            }
            res += string(cnt, j+'a');

        }
        out<<res<<endl;

	}
};


int main() {
	C solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
