/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long
#define FOR(i, a, b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i, n)  FOR(i,0,(n))


class AMaximizeTheFormula {
public:
    void solve(std::istream &in, std::ostream &out) {
      vector<int> a(3);
      REP(i, 3) in >> a[i];
      sort(a.begin(), a.end(), greater<int>());
      out << a[0] * 10 + a[1] + a[2] << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  AMaximizeTheFormula solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
