/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"

using namespace std;
#define int long long


class ACatsAndDogs {
public:
    void solve(std::istream &in, std::ostream &out) {
      int a, b, x;
      in >> a >> b >> x;
      out << (a <= x && a + b >= x ? "YES" : "NO") << endl;
    }
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
  ACatsAndDogs solver;
  std::istream &in(std::cin);
  std::ostream &out(std::cout);
  solver.solve(in, out);
  return 0;
}
