/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long


class ATwoCoins {
public:
	void solve(std::istream& in, std::ostream& out) {
    int a,b,c;
    in >> a >> b >> c;
    out << ((a + b) >= c ? "Yes" : "No" )<< endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	ATwoCoins solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
