#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(std::string S){
  long long N = S.size();

  for(long long i = 0; i < N; i++){
    for(long long j = 0; j < (N-i); j++) {
      string tmp = S;

      if(tmp.erase(i,j) == "keyence") {
        cout << YES << endl;
        return;
      }
    }
  }

  cout << NO << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
  std::cin >> S;
    solve(S);
    return 0;
}
