#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(long long N){
  long long acc = 0;
  long long tmpN = N;

  while(tmpN > 0) {
    acc += tmpN%10;
    tmpN /= 10;
  }

  cout << ((N % acc == 0) ? YES : NO) << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
    solve(N);
    return 0;
}
