#include <bits/stdc++.h>
using namespace std;
#define rep(i, N) for (long long i = 0; i < N; i++)
using ll = long long;

void solve(long long n, std::vector<long long> a) {
    vector<ll> ans;
    rep(i, n) {
        if (i % 2 == 0) {
            ans.push_back(a[i]);
        } else {
            ans.insert(ans.begin(), a[i]);
        }
    }
    if (n % 2 == 0) {
        rep(i, n) { cout << ans[i] << " "; }
    } else {
        rep(i, n) { cout << ans[n - 1 - i] << " "; }
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can
// remove this line by using your custom template)
int main() {
    long long n;
    scanf("%lld", &n);
    std::vector<long long> a(n);
    for (int i = 0; i < n; i++) {
        scanf("%lld", &a[i]);
    }
    solve(n, std::move(a));
    return 0;
}
