#include <bits/stdc++.h>
#define FOR(i, a, b) for (int i = (a); i <= (b); i++)
#define rep(i, n) FOR(i, 0, n - 1)
using namespace std;
typedef long long ll;
template <class T> inline bool dpmin(T &a, T b) {
  if (a > b) {
    a = b;
    return 1;
  }
  return 0;
}
template <class T> inline bool dpmax(T &a, T b) {
  if (a < b) {
    a = b;
    return 1;
  }
  return 0;
}

void solve(string S) {
    int ans = 0;
    ll n = S.size();
    string sub;
    ll len_sub;
    string subsub_l, subsub_r;

    for (int i = 1; i < n; i++) {
        sub = S.substr(0, i);
        if (sub.size()%2 != 0) {
            continue;
        } else {
            len_sub = sub.size() / 2;
            subsub_l = sub.substr(0, len_sub);
            subsub_r = sub.substr(len_sub, len_sub);
            if (subsub_l == subsub_r) {
                /* cout << subsub_l << " - " << subsub_r << endl; */
                if (ans < sub.size()) {
                    ans = sub.size();
                }
            }
        }
    }

    cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips:
// You use the default template now. You can remove this line by using your
// custom template)
int main() {
  string S;
  cin >> S;
  solve(S);
  return 0;
}
