/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Kishan Sairam Adapa
 */

#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#define ll long long int
#define MOD ((int)(1e9) + 7)

using namespace std;

class BFiveDishes {
public:
    void solve(istream& cin, ostream& cout) {
        vector<int> a;
        for(int i=0; i<5; i++) {
            int tp;
            cin >> tp;
            a.push_back(tp);
        }
        int min_id = -1;
        for(int i=0; i<5; i++) {
            if(a[i]%10 != 0 && min_id == -1) min_id = i;
            if(a[i]%10 != 0 && a[min_id] % 10 > a[i] % 10) min_id  = i;
        }
        for(int i=0; i<5; i++) {
            if(i == min_id) continue;
            if(a[i] % 10)
                a[i] = ((a[i]/10)+1)*10;
        }
        int sum =0;
        for(auto k: a) sum += k;
        cout << sum << '\n';
    }
};


int main() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(NULL);
    BFiveDishes solver;
    std::istream& in(std::cin);
    std::ostream& out(std::cout);
    solver.solve(in, out);
    return 0;
}
