/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author NikuKyabe
 */

#include "bits/stdc++.h"
using namespace std;
#define int long long
#define FOR(i,a,b) for(int i=(int)(a);i<(int)(b);++i)
#define REP(i,n)  FOR(i,0,(n))


class BPostalCode {
public:
	void solve(std::istream& in, std::ostream& out) {
    int a,b;
    in >> a >> b;
    string s;
    in >> s;
    REP(i,s.length()){
      if(i == a) {
        if(s[i] != '-'){
          out << "No" << endl;
          return;
        }
      }
      else{
        if(s[i] < '0' || s[i] > '9'){
          out << "No" << endl;
          return;
        }
      }
    }
    out << "Yes" << endl;
	}
};


signed main() {
  ios::sync_with_stdio(false);
  cout.tie(0);
  cout << fixed;
	BPostalCode solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
