#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long C, long long D){
    if ((A + B) > (C + D)) cout << "Left" << endl;
    else if ((A + B) < (C + D)) cout << "Right" << endl;
    else cout << "Balanced" << endl; 
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long C;
    scanf("%lld",&C);
    long long D;
    scanf("%lld",&D);
    solve(A, B, C, D);
    return 0;
}
