#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long A, long long B, std::vector<long long> P){
  long long lteqA = 0;
  long long gtAlteqB = 0;
  long long gtB = 0;

  for(long long i = 0; i < N; i++){
    if(P[i] <= A) lteqA++;
    if(P[i] > A && P[i] <= B) gtAlteqB++;
    if(P[i] > B) gtB++;
  }

  cout << min(lteqA, min(gtAlteqB, gtB)) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
  scanf("%lld",&N);
  long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  std::vector<long long> P(N);
  for(int i = 0 ; i < N ; i++){
    scanf("%lld",&P[i]);
  }
    solve(N, A, B, std::move(P));
    return 0;
}
