/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>

class abc074a {
public:
	void solve(std::istream& in, std::ostream& out) {
	    int n, a;
	    in >> n >> a;
	    out << n * n - a << std::endl;

	}
};


int main() {
	abc074a solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
