#include <bits/stdc++.h>
using namespace std;


void solve(long long Q, long long H, long long S, long long D, long long N){
    // コスパ最強なものを買う
    // 2Lで奇数だったら、1Lコスパ最強なものを買う
    Q = 4 * Q;
    H = 2 * H;
    // 1Lコスパ最強
    long long cost_1l;
    if( Q <= H && Q <= S) cost_1l = Q;
    if( H <= Q && H <= S) cost_1l = H;
    if( S <= Q && S <= H) cost_1l = S;

    // 2Lコスパ最強
    long long cost_2l = (cost_1l * 2 >= D) ? D : cost_1l*2;

    if(N % 2 == 0){
        cout << (N/2) * cost_2l << endl;
    } else { 
        cout << (N/2) * cost_2l + cost_1l << endl;
    }

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long Q;
    scanf("%lld",&Q);
    long long H;
    scanf("%lld",&H);
    long long S;
    scanf("%lld",&S);
    long long D;
    scanf("%lld",&D);
    long long N;
    scanf("%lld",&N);
    solve(Q, H, S, D, N);
    return 0;
}
