#include <bits/stdc++.h>
using namespace std;


void solve(long long Q, long long H, long long S, long long D, long long N){
  vector<long long> vec({Q*4, H*2, S});
  long long mymin = *min_element(vec.begin(), vec.end());

  if((mymin*2) > D) {
    cout << (D*(N/2))+((N%2)*mymin) << endl;
  }
  else {
    cout << mymin * N << endl;
  }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long Q;
  scanf("%lld",&Q);
  long long H;
  scanf("%lld",&H);
  long long S;
  scanf("%lld",&S);
  long long D;
  scanf("%lld",&D);
  long long N;
  scanf("%lld",&N);
    solve(Q, H, S, D, N);
    return 0;
}
