#include <bits/stdc++.h>
using namespace std;


void solve(long long A, long long B, long long K){
  long long count = 0;

  for(long long i = min(A,B); i > 0; i--){
    if(A%i == 0 && B%i == 0) count++;

    if(count == K) {
      cout << i << endl;
      return;
    }
  }
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
  scanf("%lld",&A);
  long long B;
  scanf("%lld",&B);
  long long K;
  scanf("%lld",&K);
    solve(A, B, K);
    return 0;
}
